# Generated by Django 3.2.7 on 2021-11-07 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('fio_parents', models.CharField(max_length=258)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=258)),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('accepted', 'Accepted')], default='registration', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('parent_passport', 'Parent Passport')], default='birth_certificate', max_length=70)),
                ('file', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
        ),
    ]
