# Generated by Django 3.2.7 on 2021-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='color',
            field=models.CharField(choices=[('white_10', 'White'), ('white_yellow_9', 'White Yellow'), ('yellow_8', 'Yellow'), ('yellow_green_7', 'Yellow Green'), ('green_6', 'Green'), ('green_blue_5', 'Green Blue'), ('blue_4', 'Blue'), ('blue_red_3', 'Blue Red'), ('red_2', 'Red'), ('red_black_1', 'Red Black'), ('black_1dan', 'Black 1')], default='white_10', max_length=255),
        ),
    ]
