# Generated by Django 3.2.7 on 2021-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('information', models.TextField()),
                ('images', models.URLField(max_length=999)),
            ],
        ),
    ]
