# Generated by Django 3.2.7 on 2021-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher1', 'Teacher1'), ('teacher2', 'Teacher2'), ('personal_cabinet', 'Personal Cabinet')], default='personal_cabinet', max_length=50),
        ),
    ]
