# Generated by Django 3.2.7 on 2021-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
